// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajlkwpneviaifmtwmxmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqbGt3cG5ldmlhaWZtdHdteG12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDkyNjAsImV4cCI6MjA1ODIyNTI2MH0.nNBCkXYTbiLW3KWkVVPRe31ChTFeCNvgSVz1PIqljHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);